timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  #machineType: 'N1_HIGHCPU_8'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
    args: [ 'build', '-t', 'gcr.io/wlhe-cr/mesh-base', '.' ]
    #timeout: 600s
    #entrypoint: /bin/bash

  - name: 'gcr.io/cloud-builders/docker'
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
    args: [ 'build', '-t', 'gcr.io/wlhe-cr/fortio-mesh', 'samples/fortio' ]

#  - name: 'gcr.io/kaniko-project/executor:latest'
#    args:
#      - --destination=gcr.io/$PROJECT_ID/krun:latest
#      - --cache=true
#      - --cache-ttl=24h
#    timeout: 1200s


substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  # _PULL_BASE_REF will contain the ref that was pushed to to trigger this build -
  # a branch like 'master' or 'release-0.2', or a tag like 'v0.2'.
  _PULL_BASE_REF: 'master'
