# Allow all system-authenticated KSAs to read the mesh config and root cert in istio-system for MCP.
# The config is indirectly available to pods via injection, no secrets inside.
# Istiod public cert is replicated in all namespaces and available - reading the one in istio-system to avoid
# replication details. In future we should be able to use this method instead of having the replication controller.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-system
  name: istio-autoconf
rules:
  - apiGroups: [""]
    resources:
      - "configmaps"
    resourceNames:
      - "env-asm-managed"
      - "istio-ca-root-cert"
      - "istio"
    verbs:
      - "get"
  - apiGroups: [""]
    resources:
      - "services"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: istio-system
  name: istio-autoconf-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-autoconf
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
