apiVersion: mesh.cloud.google.com/v1beta1
kind: ControlPlaneRevision
metadata:
  name: istio
  namespace: istio-system
  labels:
    mesh.cloud.google.com/managed-cni-enabled: "false"
spec:
  type: managed_service
  channel: regular
