apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fortio-tokenrequest
rules:
  - apiGroups: [""]
    resources:
      - "serviceaccounts/token"
      - "serviceaccounts"
#    resourceNames:
#      - "default"
    verbs:
      - "create"
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tokenrequest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortio-tokenrequest
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
