apiVersion: v1
kind: Service
metadata:
  name: fortio-cr-icq63pqnqq-uc
  namespace: fortio
spec:
  # Service name matches the actual service name in CloudRun.
  # This is used to acccess only the service in cloudrun, in a region. Can be used as a subset
  # TODO: auto-create this if it doesn't exist, in SNIGate
  ports:
    # Standard port for SNI routing in gateways, same as east-west gateway
    - port: 8080
      name: http
      targetPort: 15443
  selector:
    app: fortio-cr

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fortio-cr
  namespace: fortio
spec:
  host: fortio-cr-icq63pqnqq-uc.fortio.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: fortio-cr
  namespace: fortio
spec:
  metadata:
    labels:
      app: fortio-cr
    annotations:
      security.cloud.google.com/IdentityProvider: google
  template:
    ports:
      http: 8080
    serviceAccount: k8s-fortio@wlhe-cr.iam.gserviceaccount.com
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: fortio-cr-sni
  namespace: fortio
spec:
  labels:
    app: fortio-cr
  serviceAccount: default
  address: 34.136.46.192
  ports:
    http: 15443
---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: fortio
  name: fortio-cr-icq63pqnqq-uc
#  labels:
#    topology.istio.io/network: hbone
spec:
  hosts:
    - fortio-cr-icq63pqnqq-uc.fortio.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 8080
      name: http
      protocol: HTTP
      targetPort: 15443
  resolution: STATIC
  workloadSelector:
    labels:
      app: fortio-cr
#---
#
#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  namespace: fortio
#  name: local-fortio-cr-icq63pqnqq-uc
#spec:
#  hosts:
#    #- fortio-cr-icq63pqnqq-uc.a.run.app
#    - fortio-cr-icq63pqnqq-uc.fortio.svc.cluster.local
#  location: MESH_INTERNAL
#  ports:
#    - number: 8080
#      name: http
#      protocol: TLS
#  resolution: DNS
#  endpoints:
#    - address:  34.136.46.192
#      ports:
#        http: 15443
