apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NS}
  name: remote-xds-default
rules:
  - apiGroups: [""]
    resources:
      - "serviceaccounts/token"
      #  - "serviceaccounts"
    resourceNames:
      - "default"
    verbs:
      - "create"
      - "get"
  - apiGroups: [""]
    resources:
      - "configmaps"
    resourceNames:
      - "istio-ca-root-cert"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ${NS}
  name: remote-xds-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remote-xds-default
subjects:
  - kind: User
    name: k8s-${NS}@${PROJECT_ID}.iam.gserviceaccount.com
