# Add the hbone listener and cluster, instead of using a custom bootstrap

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hbone-in
  namespace: fortio
spec:
  workloadSelector:
    labels:
      app: fortio-cr

  configPatches:
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster: { }
      patch:
        operation: ADD
        value: # Cluster spec
          "name": "hb_local_mtls"
          "connect_timeout": "2s"
          "typed_extension_protocol_options":
            "envoy.extensions.upstreams.http.v3.HttpProtocolOptions":
              "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
              "explicit_http_config":
                "http2_protocol_options":
                  "allow_connect": true

          "load_assignment":
            cluster_name: "hb_local_mtls"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      "address":
                        "socket_address":
                          "address": "127.0.0.1"
                          "port_value": 8443

    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster: { }
      patch:
        operation: ADD
        value:
          "name": "hb_local_tcp_22"
          "connect_timeout": "2s"
          "load_assignment":
            cluster_name: "hb_local_tcp_22"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      "address":
                        "socket_address":
                          "address": "127.0.0.1"
                          "port_value": 15022

    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster: { }
      patch:
        operation: ADD
        value: # Cluster spec
          "name": "hb_local_tcp_8080"
          "connect_timeout": "2s"
          "load_assignment":
            cluster_name: "hb_local_tcp_8080"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      "address":
                        "socket_address":
                          "address": "127.0.0.1"
                          "port_value": 8080


    - applyTo: LISTENER
      match:
        context: SIDECAR_OUTBOUND
        listener: { }
      patch:
        operation: ADD
        value: {
          "name": "hbone-h2c",
          "address": {
            "socket_address": {
              "protocol": "TCP",
              "address": "0.0.0.0",
              "port_value": 13009
            }
          },
          "filter_chains": [
            {
              "filters": [
                {
                  "name": "envoy.filters.network.http_connection_manager",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                    "stat_prefix": "hbone-h2c",
                    "route_config": {
                      "name": "hbone_route",
                      "virtual_hosts": [
                        {
                          "name": "local_service",
                          "domains": [
                              "*"
                          ],
                          "routes": [
                            {
                              "match": {
                                "prefix": "/_hbone/mtls",
                                "headers": [
                                  {
                                    "name": ":method",
                                    "exact_match": "POST"
                                  }
                                ]
                              },
                              "route": {
                                "cluster": "hb_local_mtls",
                                "upgrade_configs": [
                                  {
                                    "upgrade_type": "CONNECT",
                                    "connect_config": {
                                      "allow_post": true
                                    }
                                  }
                                ]
                              }
                            },
                            {
                              "match": {
                                "prefix": "/_hbone/22",
                                "headers": [
                                  {
                                    "name": ":method",
                                    "exact_match": "POST"
                                  }
                                ]
                              },
                              "route": {
                                "cluster": "hb_local_tcp_22",
                                "upgrade_configs": [
                                  {
                                    "upgrade_type": "CONNECT",
                                    "connect_config": {
                                      "allow_post": true
                                    }
                                  }
                                ]
                              }
                            },
                            {
                              "match": {
                                "prefix": "/config_dump",
                              },
                              "route": {
                                "cluster": "prometheus_stats"
                              }
                            },
                            {
                              "match": {
                                "prefix": "/",
                              },
                              "route": {
                                "cluster": "hb_local_tcp_8080"
                              }
                            }
                          ]
                        }
                      ]
                    },
                    "http_filters": [
                      {
                        "name": "envoy.filters.http.router"
                      }
                    ],
                    "http2_protocol_options": {
                      "allow_connect": true
                    }
                  }
                }
              ]
            }
