name: Go
on: [push]

env:
  GO111MODULE: on
  #KO_DOCKER_REPO: ghcr.io/costinm/krun
  #KRUN_IMAGE: ghcr.io/costinm/krun/krun:latest

jobs:
  build-ko:
    name: Build with ko
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: What
        run:
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish -t ${{ env.BRANCH }} -B ./

#  build-docker:
#    name: Build-in-docker
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          #registry: docker.pkg.github.com
#          #username: ${{ github.actor }}
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      -
#        name: push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          context: .
#          tags: |
#            ghcr.io/costinm/cert-ssh/sshd:latest
