---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas: 1
  template:
    metadata:
      annotations:
        #sidecar.istio.io/logLevel: "TRACE"
        #sidecar.istio.io/enableCoreDump: "true"
        # For debugging
        sidecar.istio.io/privileged: "true"
        #sidecar.istio.io/debug: "true"
        #sidecar.istio.io/componentLogLevel: "config:trace,http2:trace,init:trace,grpc:trace,upstream:trace"

        # Override container ports
        #traffic.sidecar.istio.io/includeInboundPorts: "*"
        sidecar.istio.io/proxyCPU: {{ .Values.proxyCPU }}

      labels:
        app: {{ .Values.app }}
        version: v1
        istio.io/rev: canary
    spec:
      containers:
      - name: fortio
        image: {{ .Values.fortioImage | default "costinm/fortio:latest" }}
        ports:
         - containerPort: 8080
           name: http
         - containerPort: 8081
           name: grpc
         - containerPort: 8079
        args:
          - server
        resources:
          requests:
            cpu: {{ .Values.appCPU }}
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1G"

