apiVersion: networking.k8s.io/v1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortio
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
    - host: fortio-ingress.{{ .Values.domain }}
      http:
        paths:
          - #path: /.*
            # v1
            path: /
            pathType: Prefix
            backend:
              service:
                name: fortio
                port:
                  number: 8080
              # Beta1:
              #serviceName: fortio
              #servicePort: 8080
