---
apiVersion: v1
kind: Service
metadata:
  name: fortio
spec:
  ports:
    - port: 8080
      name: http-echo
  selector:
    app: fortio

---
apiVersion: v1
kind: Service
metadata:
  name: fortio-cli
spec:
  ports:
    - port: 8080
      name: http-echo
  selector:
    app: cli-fortio
