apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - port:
        number: 9999
        protocol: HTTP
        name: http-fortio
      captureMode: NONE
      hosts:
        - fortio/fortio.fortio.svc
    - hosts:
        - "fortio/*"
        - "test/*"
        - "./*"
        - "httpbin/*"
